import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto( 
    {
      subsets: ['latin'],
      weight: ['400', '500', '700'],
      style: ['italic', 'normal']
    }
  )

export const metadata: Metadata = {
  title: "Rikkei Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
      <head>
        <link rel="icon" href="https://learn.rikkeiacademy.com/favicon.ico.png" />
      </head>
    </html>
  );
}
